opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline

  - empty_count
  - explicit_init
  - extension_access_modifier

  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping

  - implicit_return

  - let_var_whitespace

  - multiline_parameters

  - nimble_operator - discuss
  - number_separator

  - object_literal
  - overridden_super_call

  - private_outlet
  - prohibited_super_call

  - redundant_nil_coalescing

  - unneeded_parentheses_in_closure_argument

  - vertical_parameter_alignment_on_call

excluded:
  - Carthage
  - Pods
  - Generated

line_length: 128

type_body_length:
  - 500 # warning
  - 700 # error

file_length:
  warning: 500
  error: 1200

function_parameter_count:
  error: 5

identifier_name:
  excluded:
    - id
    - ok
    - URL
    - x
    - y
    - z

warning_threshold: 1